version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  file-lines:
    enabled: false
  method-complexity:
    enabled: true
    config:
      threshold: 15
plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/tasks/"
